name: Final Start Deploy Trigger equivalent to 203-build-and-megre

on:
  workflow_dispatch:

jobs:
  deploystarttrigger:
    permissions: write-all
    uses: ./.github/workflows/finaldeployt.yml
    with:
      image_tag: latest
      region: "*"
      silo_id: "*"
      stage: uat
      
