name: Final Start Deploy Trigger equivalent to 203-build-and-megre

on:
  workflow_dispatch:

jobs:
  deploystarttrigger:
    permissions: write-all
    uses: ./.github/workflows/finaldeployt.yml
    strategy:
      matrix:
      
        region: ["region-1","region-2"]
        silo: ["SILO-ONE","SILO-TWO"]
    with:
      image_tag: latest
      region: ${{ matrix.region }}
      silo_id: ${{ matrix.silo }}
      stage: uat
      
