name: New test

on:
  workflow_dispatch:
    inputs:
      new:
        type: string
        required: true
        default: "1" 
  
  workflow_call:
    inputs:
      new:
        type: string
        required: true
        default: "1" 
  

jobs:
  display: 
    if: ${{ github.event_name == 'workflow_call' }} || ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Display input number using script conditionals
        run: |
          if [ "${{ github.event.inputs.new || inputs.new}}" == "1" ]; then
            echo "the number is ${{ github.event.inputs.new || inputs.new }}"
          elif [ "${{ github.event.inputs.new }}" == "2" ]; then
            echo "the number is ${{ github.event.inputs.new || inputs.new }}"
          elif [ "${{ github.event.inputs.new }}" == "*" ]; then
            echo "the number is ${{ github.event.inputs.new || inputs.new }}"
          else
            echo "the number is ${{ github.event.inputs.new || inputs.new }}"
          fi

  display1: 
    if: ${{ github.event_name == 'workflow_call' }} || ${{ github.event_name == 'workflow_dispatch' }} && ${{ github.event.inputs.new == '*' }} || ${{ inputs.new == '*' }}
    runs-on: ubuntu-latest
    steps:
      - name: Display input number using script conditionals
        run: |
          echo this is from "1"
          echo this is from "2"        
