name: rev_merge 

on: 
  workflow_dispatch: 


jobs: 
  merge: 
    strategy:
       matrix: 
         region: ["us-west-2","eu-east-2"]
         stage: [ "staging" ] 
         silo: ["silo-1", "silo-2"]
    uses: ./.github/workflows/reusable.yml 
    with: 
      region : ${{ matrix.region }} 
      stage: ${{ matrix.stage }} 
      silo: ${{ matrix.silo }}
    
