name: Event Trigger and Reusable Workflow Caller

on:
  release:
    types: [released, prereleased]
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  release_released:
    if: ${{ github.event_name == 'release' && github.event.action == 'released' }}
    uses: ./.github/workflows/reusable.yml
    with:
      region: "us-west-1"
      stage: "production"
      silo: "frontend"

  release_prereleased:
    if: ${{ github.event_name == 'release' && github.event.action == 'prereleased' }}
    uses: ./.github/workflows/reusable.yml
    with:
      region: "us-east-1"
      stage: "uat"
      silo: "backend"

  workflow_dispatch_job:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/reusable.yml
    with:
      region: "eu-central-1"
      stage: "staging"
      silo: "api"

  workflow_call_job:
    if: ${{ github.event_name == 'workflow_call' }}
    uses: ./.github/workflows/reusable.yml
    with:
      region: "ap-south-1"
      stage: "staging"
      silo: "misc"
